spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxPoolSize: 3
      minIdle: 1
      auto-commit: true
      connection-test-query: SELECT 1
      pool-name: DatebookHikariCP
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mapper/*
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: debug